APP_BOX_ACTIONS, AUTH_INVITE, AUTH_USERNAME, AUTH_PASSWORD, AUTH_VALIDATION, APP_MENU_CASES, APP_BUILDINGS_CASES, APP_BUILDING_CASES, APP_BOXES_CASES, APP_ROOMS_CASES, APP_BOX_FIRST_DATE_HANDLE, APP_BOX_SECOND_DATE_HANDLE = range(
    12)
